[jobs.run]
command = [
    'shuttle', "run"
]
need_stdout = true
allow_warnings = true
background = true

[jobs.kill-windows]
command = ['taskkill', '/f', '/im', 'plumpen.exe']
need_stdout = true

[keybindings]
k = "job:kill-windows"